# Generated by Django 5.1.6 on 2025-06-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['state_name', 'state_code'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AddField(
            model_name='country',
            name='valided',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_source',
            field=models.CharField(choices=[('all_events_in', 'All Events In'), ('eventbrite', 'Eventbrite'), ('user_submitted', 'User Submitted'), ('serp_api_google_event', 'Google Event Search'), ('artidea', 'Art Idea'), ('luma', 'Luma'), ('ticketmaster', 'Ticketmaster')], default='serp_api_google_event', max_length=50),
        ),
    ]
