# Generated by Django 5.1.6 on 2025-06-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_location_options_country_valided_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('release_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('commit_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('commit_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'App Versions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
