# Generated by Django 5.1.6 on 2025-06-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_appversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
