# Generated by Django 5.1.6 on 2025-07-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_source',
            field=models.CharField(choices=[('all_events_in', 'All Events In'), ('eventbrite', 'Eventbrite'), ('user_submitted', 'User Submitted'), ('serp_api_google_event', 'Google Event Search'), ('artidea', 'Art Idea'), ('added_by_admin', 'Added by Admin'), ('luma', 'Luma'), ('ticketmaster', 'Ticketmaster')], default='serp_api_google_event', max_length=50),
        ),
    ]
